### PR TITLE
Supply an alternative REC data download at runtime

### PR DESCRIPTION
**Pull request by LukeParky**
DESCRIPTION OF PR:
This is Cherry-picked from the S3 bucket branch.

Please smoke test this by running ensuring the new alternative download gets added to the database. My debugger was causing it to take a long time but it looks resolved.

## Developer Checklist
- [x] Make code change
- [ ] Update tests
  - [ ] Update / create new tests
  - [ ] Ensure these tests have the expected behaviour
  - [ ] Test locally and ensure tests are passing
- [ ] Update documentation
  - [ ] Readme
  - [ ] Docstrings
  - [ ] Comments
  - [ ] Wiki

## Reviewer Checklist
- [ ] Check new code for code smells
- [ ] Check new tests
  - [ ] Ensure adequate coverage
  - [ ] Check for code smells within tests
- [ ] Check if documentation needs updating
  - [ ] Readme
  - [ ] Docstrings
  - [ ] Comments
  - [ ] Wiki

### CODE REVIEW

**Review by caseyli92 — CHANGES_REQUESTED** [review]
The REC backup data was retrieved in approximately 2 minutes. Working for me.

**Comment by caseyli92** [comment]
> The REC backup data was retrieved in approximately 2 minutes. Working for me.

Oops, did you mean that adding it to the database was causing the delay, not the download?

**Comment by caseyli92** [comment]
> > The REC backup data was retrieved in approximately 2 minutes. Working for me.
> 
> Oops, did you mean that adding it to the database was causing the delay, not the download?

Occasionally, uploading this data to the database takes an excessively long time. It's been hanging for about 30 minutes now, although it's not always this slow.

**Comment by caseyli92** [comment]
> The REC backup data was retrieved in approximately 2 minutes. At times, uploading this data to the database can be quite slow. It's currently been hanging for about 30 minutes, though it doesn't consistently behave this way. Any thoughts?

**Comment by LukeParky** [comment]
> The REC backup data was retrieved in approximately 2 minutes. At times, uploading this data to the database can be quite slow. It's currently been hanging for about 30 minutes, though it doesn't consistently behave this way. Any thoughts?

I also experienced it intermittently and wasn't sure why. It doesn't seem to be caused by these changes as far as I can tell. It seems to be much worse when using the pycharm debugger.

**Review by caseyli92 — APPROVED** [review]

**Comment by LukeParky** [comment]
Choosing to merge this. It appears to only affect development mode and is very intermittent

**Pull request merged**
