### PR TITLE
Add github action to check for issues blocked by other issues

### PR DESCRIPTION
**Pull request by LukeParky**
DESCRIPTION OF PR:
The github action here searches through issues and adds blocked labels.
It also adds blocked-by and blocks links.

See example repo using this action in the issues and PRs of this repo: https://github.com/Levi-Lesches/blocking-issues-test

## Developer Checklist
- [x] Make code change
- [ ] Update documentation (Considering leaving this because we are going to need a large restructuing of the documentation soon)
  - [ ] Readme
  - [ ] Wiki 

## Reviewer Checklist
- [x] Check new code for code smells
- [ ] ~Ensure adequate test coverage~
- [ ] ~Check if documentation needs updating~
  - [ ] ~Readme~
  - [ ] ~Docstrings~
  - [ ] ~Comments~
  - [ ] ~Wiki~
Only worried about code changes. We may note it in the Wiki/README at some point but not pressing

### CODE REVIEW

**Comment by LukeParky** [comment]
Another interesting action would be to automatically add new issues to the GH project.
https://github.com/marketplace/actions/assign-to-one-project

**Review by rosepearson — APPROVED** [review]
Looks good! A good option to include for all types. Only question is if it makes sense for deleted? I'm assuming this will lead it to be removed... so would make sense

**Comment by rosepearson** [comment]
> Another interesting action would be to automatically add new issues to the GH project. https://github.com/marketplace/actions/assign-to-one-project

Nice find @LukeParky. Yes - I agree that could be a great addition.

**Comment by LukeParky** [comment]
> Looks good! A good option to include for all types. Only question is if it makes sense for deleted? I'm assuming this will lead it to be removed... so would make sense

Yes that's what I was thinking too, so I am going to merge it as is

>Nice find @LukeParky. Yes - I agree that could be a great addition.

I'm making a new issue for this, with low priority. @caseyli92 can implement it if she gets free time. It would be a good first step to understanding GH actions. #43

**Pull request merged**
